export interface ScenarioAssumptions { revenueGrowthPct: number; plannedHires: number; infrastructureGrowthPct: number; }
export const actuals = { arr: 4_800_000, recognizedRevenueYtd: 2_100_000, cashBalance: 5_000_000, monthlyNetBurn: 250_000, headcount: 70, overdueAr60: 180_000, baselineAnnualRevenue: 4_200_000, baselineAnnualPayroll: 5_300_000, baselineInfrastructureCost: 1_100_000, baselineOtherOpex: 1_800_000, baselineOperatingCashOutflow: 8_200_000 };
export const presets: Record<"base"|"upside"|"downside", ScenarioAssumptions> = { base:{ revenueGrowthPct:30, plannedHires:15, infrastructureGrowthPct:20 }, upside:{ revenueGrowthPct:45, plannedHires:20, infrastructureGrowthPct:25 }, downside:{ revenueGrowthPct:15, plannedHires:25, infrastructureGrowthPct:30 } };
export const contractDemo = { customerName:"Enterprise Client A", subscriptionAmount:120_000, implementationFee:15_000, amountInvoiced:135_000, cashCollected:100_000 };
export const euro = (n:number) => new Intl.NumberFormat("en-IE", {style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
export const euroCompact = (n:number) => n >= 1_000_000 ? `€${(n/1_000_000).toFixed(1)}m` : `€${Math.round(n/1000)}k`;
export function getDecisionFlags(data=actuals) { const flags=[]; if(data.overdueAr60>150_000) flags.push({title:"Collections risk",message:"€180k of enterprise receivables are more than 60 days overdue. Review customer concentration and collection actions."}); if(data.cashBalance/data.monthlyNetBurn<21) flags.push({title:"Runway watch",message:"Runway is approaching the 18-month planning threshold. Sequence hiring against contracted revenue conversion."}); return flags.slice(0,3); }
export function getRevenueBridge(contract=contractDemo, elapsedMonths=3) { const recognized = contract.subscriptionAmount/12*elapsedMonths; return { contracted:contract.subscriptionAmount+contract.implementationFee, invoiced:contract.amountInvoiced, recognized, deferred:Math.max(0,contract.subscriptionAmount-recognized), collected:contract.cashCollected }; }
export function modelScenario(a:ScenarioAssumptions) { const forecastRevenue=actuals.baselineAnnualRevenue*(1+a.revenueGrowthPct/100); const incrementalPayroll=a.plannedHires*110_000; const forecastPayroll=actuals.baselineAnnualPayroll+incrementalPayroll; const forecastInfrastructureCost=actuals.baselineInfrastructureCost*(1+a.infrastructureGrowthPct/100); const infrastructureIncrement=forecastInfrastructureCost-actuals.baselineInfrastructureCost; const forecastCashOutflow=actuals.baselineOperatingCashOutflow+incrementalPayroll+infrastructureIncrement; const forecastMonthlyBurn=Math.max(0,forecastCashOutflow-forecastRevenue)/12; const forecastEndingCash=actuals.cashBalance-forecastMonthlyBurn*12; const runwayMonths=forecastMonthlyBurn<=0?Infinity:actuals.cashBalance/forecastMonthlyBurn; const baseRunway=20; let narrative=`At ${a.revenueGrowthPct}% growth with ${a.plannedHires} planned hires, runway is ${Number.isFinite(runwayMonths)?`${runwayMonths.toFixed(1)} months`:"cash generative"}. `; narrative += runwayMonths<18?"Sequence hiring against signed revenue and tighten collections before committing to the full cost base.":runwayMonths<baseRunway?"The plan remains fundable, but leadership should stage hiring against revenue conversion milestones.":"The scenario preserves strategic flexibility; validate capacity needs before accelerating the hiring plan."; return {forecastRevenue,incrementalPayroll,forecastPayroll,forecastInfrastructureCost,forecastTotalOpex:forecastPayroll+forecastInfrastructureCost+actuals.baselineOtherOpex,forecastMonthlyBurn,forecastEndingCash,runwayMonths,narrative}; }
